Repository UMC-BRUSHWORK/frontend, pull requests merged in 2024-02, with the labels that each got.

#119 feat: 카테고리 컴포넌트 수정 완료
  src/components/common/category/Category.jsx
  src/components/common/category/Category.style.js
  src/components/common/category/CategoryList.jsx
  src/constants/categoryDummy.js
  src/constants/deliveryDummy.js
Labels: 컴포넌트, 공통, 완성

#124 feat: 구매자 선택 모달 생성
  src/components/modal/purchased/Buyer.Style.js
  src/components/modal/purchased/Buyer.jsx
  src/components/modal/purchased/PurchasedModal.jsx
  src/components/modal/purchased/PurchasedModal.style.js
Labels: 컴포넌트, 완성

#125 feat: 신고하기 모달 생성
  src/components/modal/report/Reason.jsx
  src/components/modal/report/Reason.style.js
  src/components/modal/report/ReportModal.jsx
  src/components/modal/report/ReportModal.style.js
  src/constants/reportDummy.js
Labels: 컴포넌트, 공통, 완성

#129 fix: 마이페이지 컴포넌트 크기 수정
  src/components/common/button/SettingButton.style.js
  src/components/common/menu/menu.style.js
  src/components/common/myPage/PurchaseReviewList.jsx
  src/components/common/myPage/PurchaseReviewList.style.js
  src/pages/myPage/MyPage.jsx
Labels: 컴포넌트, 마이페이지, 완성

#131 feat: 카테고리 컴포넌트 완성
  src/components/common/category/Category.jsx
Labels: 컴포넌트, 공통, 완성

#135 feat: register api 연동
  src/apis/postRegister.js
  src/pages/auth/SignUp.jsx
Labels: 기능, 로그인

#142 Feature/#136
  package-lock.json
  package.json
  src/Router.jsx
  src/apis/getProduct.js
  src/apis/getProductList.js
  src/components/common/artwork/ArtWork.jsx
  src/components/common/artworkList/ColumnArtworkList.jsx
  src/components/common/artworkList/RowArtWorkList.jsx
  src/components/common/backButton/BackButton.jsx
  src/components/common/topbar/PurchasedTopbar.jsx
  src/components/common/topbar/SearchTopbar.jsx
  src/components/common/topbar/Topbar.jsx
  src/components/common/topbar/Topbar.style.js
  src/components/mypage/LoginStatus.jsx
  src/constants/artWorkDummy.js
  src/constants/myArtWorkDummy.js
  src/pages/artist/ArtWorksList.jsx
  src/pages/artist/Artist.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.style.js
  src/pages/artwork/artworkDetail/MyArtworkDetail.jsx
  src/pages/favorites/Favorites.jsx
  src/pages/main/Main.jsx
  src/pages/main/Seach.jsx
  src/styles/font.js
  yarn.lock
Labels: 기능, 공통

#139 feat: 작품 등록 페이지 수정
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
  src/pages/artwork/artworkUpload/ArtworkUpload.style.js
Labels: 페이지, 완성

#141 fix: 마이페이지 크기 재설정, 내 작품 favorite 안보이게 수정
  src/apis/postRegister.js
  src/components/common/artwork/ArtWork.jsx
  src/components/common/button/PurchaseReviewButton.style.js
  src/components/common/myPage/MyArtWorkList.jsx
  src/components/mypage/LoginStatus.style.js
  src/pages/auth/SignUp.jsx
Labels: 페이지, 마이페이지, 완성

#145 Feature/#6
  src/assets/index.js
  src/assets/warning.svg
  src/components/common/toast/Toast.jsx
  src/components/common/toast/Tost.style.js
  src/hooks/useToast.js
  src/pages/auth/SignIn.jsx
Labels: 기능, 공통

#152 feat: 토큰 저장, 접근권한 설정
  src/components/common/menu/menu.jsx
  src/components/modal/LoginModal.jsx
  src/components/modal/LoginModal.style.js
  src/components/mypage/LogoutStatus.jsx
  src/components/mypage/LogoutStatus.style.js
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
  src/pages/auth/SignIn.jsx
  src/pages/chatting/ChattingList.jsx
  src/pages/favorites/Favorites.jsx
  src/pages/main/Main.jsx
  src/pages/myPage/MyPage.jsx
  src/recoil/atom.jsx
Labels: 기능

#157 feat: 작품 등록 완료
  src/apis/postProduct.js
  src/components/common/category/CategoryList.jsx
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
Labels: 기능, 작품, 완성

#161 fix: 카테고리, 배송방식 선택 값으로 변경, authorId, nickname 불러오기
  .env
  src/apis/api.js
  src/components/common/artwork/ArtWork.jsx
  src/components/common/category/Category.jsx
  src/components/common/category/CategoryList.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
Labels: 기능, 작품, 완성

#163 fix: 새로고침 시 로그인 상태 유지
  src/components/common/menu/menu.jsx
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
  src/pages/auth/SignIn.jsx
  src/pages/chatting/ChattingList.jsx
  src/pages/favorites/Favorites.jsx
  src/pages/myPage/MyPage.jsx
  src/recoil/atom.jsx
  src/utils/isLogin.jsx
Labels: 로그인, 버그 수정

#170 feature: 채팅 기본기능 추가
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/api2.js
  src/apis/chatList.js
  src/apis/chatLog.js
  src/apis/createChattingRoom.js
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatList.style.js
  src/components/chatting/ChattingInput.jsx
  src/components/chatting/ChattingInput.style.js
  src/components/chatting/infoBar/InfoBar.jsx
  src/components/chatting/infoBar/InfoBar.style.js
  src/components/chatting/input/ChattingInput.jsx
  src/components/chatting/input/ChattingInput.style.js
  src/components/chatting/messages/Messages.jsx
  src/components/chatting/messages/message/Message.jsx
  src/components/chatting/messages/message/Message.style.js
  src/components/mypage/LoginStatus.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.style.js
  src/pages/auth/Auth.style.js
  src/pages/auth/SignIn.jsx
  src/pages/chatting/Chatting.jsx
  src/pages/chatting/Chatting.style.js
  src/pages/chatting/ChattingList.jsx
  src/pages/myPage/MyPage.jsx
  src/recoil/atom.jsx
  src/utils/dateFormatter.js
  src/utils/isLogin.js
  yarn.lock
Labels: 채팅

#175 feat: 채팅 무한스크롤
  package.json
  src/apis/chatList.js
  src/apis/chatLog.js
  src/components/chatting/ChatList.jsx
  src/components/chatting/infoBar/InfoBar.jsx
  src/components/chatting/messages/Messages.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/chatting/Chatting.jsx
  yarn.lock
Labels: 기능, 채팅

#178 feature: 채팅 날짜별 기능
  src/components/chatting/infoBar/InfoBar.jsx
  src/components/chatting/messages/Messages.jsx
  src/components/chatting/messages/message/Message.jsx
  src/components/chatting/messages/message/Message.style.js
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/chatting/Chatting.jsx
Labels: 기능, 채팅

#182 feat: 작품 상세 페이지 하단 버튼 api 연동
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
Labels: api

#181 feature: 작가 작품만 불러오기 api 연동
  src/apis/getProductList.js
  src/pages/artist/ArtWorksList.jsx
  src/pages/artist/Artist.jsx
Labels: api

#185 feat: 작품 등록 원칙 추가
  package.json
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
  src/pages/artwork/artworkUpload/ArtworkUpload.style.js
  src/styles/color.js
  yarn.lock
Labels: 기능, 작품, 완성

#186 feat: 판매완료 기능 연결 및 api 연동
  src/apis/getChatBuyer.js
  src/apis/getChatBuyerList.js
  src/apis/patchDeal.js
  src/components/artwork/CompleteBtn.jsx
  src/components/modal/purchased/Buyer.Style.js
  src/components/modal/purchased/Buyer.jsx
  src/components/modal/purchased/PurchasedModal.jsx
  src/components/modal/purchased/PurchasedModal.style.js
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
Labels: 완성, api

#188 feat: 채팅 읽음/안읽음
  src/apis/api2.js
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatList.style.js
  src/components/chatting/infoBar/InfoBar.jsx
  src/components/chatting/messages/Messages.jsx
  src/components/chatting/messages/message/Message.jsx
  src/components/chatting/messages/message/Message.style.js
  src/index.jsx
  src/pages/chatting/Chatting.jsx
  yarn.lock
Labels: 기능, 채팅, 미완성

#190 Feature/#148
  src/components/common/artworkList/FavorList.jsx
  src/components/favorite/Favorite.jsx
  src/pages/favorites/Favorites.jsx
Labels: api

#196 feat: 메인, 관심작품 페이지 무한스크롤 구현 완료
  src/pages/favorites/Favorites.jsx
  src/pages/main/Main.jsx
Labels: 기능, 페이지

#194 feat: 작품 신고 기능
  src/apis/postReport.js
  src/components/common/toast/Tost.style.js
  src/components/modal/report/Reason.jsx
  src/components/modal/report/ReportModal.jsx
  src/components/modal/report/ReportModal.style.js
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
Labels: 기능, 작품, 완성

#203 feat: 검색 기능
  src/apis/getSearchProduct.js
  src/components/common/topbar/SearchTopbar.jsx
  src/components/common/topbar/Topbar.style.js
  src/pages/main/Seach.jsx
  src/pages/main/Search.style.js
  src/styles/color.js
Labels: 기능, 작품
