Repository UMC-BRUSHWORK/frontend, pull requests merged in 2024-01, with the labels that each got.

#32 Feature/#29
  src/Components/modal/ModifyInfo.jsx
  src/Components/modal/ModifyInfo.style.js
  src/Router.jsx
  src/styles/color.js
  src/styles/font.js
Labels: 컴포넌트, 마이페이지

#33 Feature/#30
  src/App.jsx
  src/Components/modal/Logout.jsx
  src/Components/modal/Logout.style.js
Labels: 컴포넌트, 마이페이지

#34 Feature/#31
  src/Components/modal/LoginModal.jsx
  src/Components/modal/LoginModal.style.js
Labels: 컴포넌트, 마이페이지

#55 작가 상세 페이지
  src/Router.jsx
  src/components/artist/dropdown/Dropdown.jsx
  src/components/common/artwork/ArtWork.jsx
  src/components/common/artwork/ArtWork.style.js
  src/components/common/artworkList/ColumnArtworkList.jsx
  src/components/common/artworkList/RowArtWorkList.jsx
  src/components/common/profile/Profile.style.jsx
  src/pages/Artist.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/artist/ArtWorksList.jsx
  src/pages/artist/Artist.jsx
  src/pages/artist/Artist.style.js
  src/pages/artist/ArtistReviewList.jsx
  src/pages/main/Main.jsx
  src/pages/main/Main.style.js
Labels: 페이지, 작가, 완성

#51 feat: 마이페이지 구매내역 작품정보 컴포넌트
  src/Router.jsx
  src/assets/art_works/art_work_7.png
  src/assets/art_works/art_work_8.png
  src/components/common/artwork/PurchasedArtWorkInfo.jsx
  src/components/common/artwork/PurchasedArtWorkInfo.style.js
  src/components/common/button/ReviewWriteButton.style.js
  src/styles/color.js
  src/styles/font.js
  yarn.lock
Labels: 컴포넌트, 마이페이지, 완성

#53 feat: 후기작성, 후기업로드 작품 정보 컴포넌트 생성
  src/assets/art_works/art_work_9.png
  src/components/common/artwork/ArtWorkInfo.jsx
  src/components/common/artwork/ArtWorkInfo.style.js
  src/styles/color.js
Labels: 마이페이지, 완성

#68 feat: ArtWork 컴포넌트 수정
  src/assets/favorite_off.svg
  src/assets/favorite_on.svg
  src/assets/index.js
  src/components/common/artwork/ArtWork.jsx
  src/components/common/artwork/ArtWork.style.js
  src/components/common/artworkList/ColumnArtworkList.jsx
  src/components/common/artworkList/RowArtWorkList.jsx
  src/pages/artist/ArtWorksList.jsx
Labels: 컴포넌트, 공통, 완성

#83 Feature/#75
  src/Router.jsx
  src/pages/myPage/MyPage.jsx
Labels: 페이지, 마이페이지, 미완성

#64 fix: 헤더, 하단네비 수정
  src/components/common/bottomNav/BottomNav.jsx
  src/components/common/bottomNav/BottomNav.style.js
  src/components/common/header/Header.jsx
  src/components/common/header/Header.style.js
  src/styles/color.js
  src/styles/font.js
Labels: 컴포넌트, 공통, 완성, 버그 수정

#70 feat: 작가 상세 - 후기 페이지
  src/components/artist/reviewList/ReviewList.jsx
  src/components/artist/temperature/Temperature.jsx
  src/components/artist/temperature/Temperature.style.js
  src/components/common/artworkList/RowArtWorkList.jsx
  src/pages/artist/ArtistReviewList.jsx
  src/styles/color.js
Labels: 페이지, 작가, 완성

#71 feat: 관심 작품 페이지
  src/Router.jsx
  src/pages/Favorites.jsx
  src/pages/favorites/Favorites.jsx
  src/pages/favorites/Favorites.style.js
Labels: 페이지, 홈, 완성

#69 feat: 마이페이지 메뉴 컴포넌트
  src/assets/account_box.svg
  src/assets/contract.svg
  src/assets/logout.svg
  src/assets/shopping_bag.svg
  src/components/common/menu/menu.jsx
  src/components/common/menu/menu.style.js
  src/pages/Mypage.jsx
  src/pages/myPage/Purchased.jsx
  src/pages/myPage/Settings.jsx
  src/styles/color.js
Labels: 컴포넌트, 마이페이지, 완성

#79 feat: Topbar 컴포넌트 생성
  src/assets/images/arrow_back.svg
  src/assets/images/notif.svg
  src/assets/images/search.svg
  src/components/common/topbar/Topbar.jsx
  src/components/common/topbar/Topbar.style.js
Labels: 컴포넌트, 공통, 완성

#72 feat: 마이페이지 거래후기 컴포넌트
  src/components/common/button/PurchaseReviewButton.jsx
  src/components/common/button/PurchaseReviewButton.style.js
  src/components/common/myPage/PurchaseReview.jsx
  src/components/common/myPage/PurchaseReview.style.js
  src/components/common/myPage/PurchaseReviewList.jsx
  src/components/common/myPage/PurchaseReviewList.style.js
Labels: 컴포넌트, 마이페이지, 완성

#78 feat: 카테고리 컴포넌트 수정
  src/components/common/category/Category.jsx
  src/components/common/category/Category.style.js
Labels: 컴포넌트, 공통, 완성

#80 feat: 작품 등록 페이지 생성
  src/assets/images/photo.svg
  src/components/common/category/Category.jsx
  src/pages/artworkUpload/ArtworkUpload.jsx
  src/pages/artworkUpload/ArtworkUpload.style.js
Labels: 페이지, 완성

#82 feat: 상세설명 컴포넌트 수정
  src/components/common/description/Description.jsx
  src/components/common/description/Description.style.js
Labels: 컴포넌트, 공통, 완성

#90 feat: 검색 페이지 기본 틀
  src/Router.jsx
  src/pages/Seach.jsx
  src/pages/main/Seach.jsx
  src/pages/main/Search.style.js
Labels: 페이지, 홈, 미완성

#88 feat: 내 프로필 수정 모달 생성
  src/assets/photo_camera.svg
  src/assets/profile_image.png
  src/components/modal/ModifyProfile.jsx
  src/components/modal/ModifyProfile.style.js
Labels: 컴포넌트, 마이페이지, 완성

#94 Refactor/#91
  src/Router.jsx
  src/assets/arrow_back.svg
  src/assets/artist/arrow_drop_down.svg
  src/assets/artist/dissatisfied.svg
  src/assets/artist/satisfied.svg
  src/assets/artwork/edit.svg
  src/assets/artwork/emergency.svg
  src/assets/artwork/photo.svg
  src/assets/artwork/right_button_black.svg
  src/assets/artwork/right_button_grey.svg
  src/assets/brushwork_logo.svg
  src/assets/default_images/profile.png
  src/assets/dummy_images/profile_image.png
  src/assets/images/Logo.png
  src/assets/images/favorite.svg
  src/assets/index.js
  src/assets/myPage/account_box.svg
  src/assets/myPage/contract.svg
  src/assets/myPage/logout.svg
  src/assets/myPage/settings.svg
  src/assets/myPage/shopping_bag.svg
  src/assets/notif.svg
  src/assets/photo_camera.svg
  src/assets/search.svg
  src/components/common/artwork/ArtWork.jsx
  src/components/common/bottomNav/BottomNav.jsx
  src/components/common/button/MyArtWork.jsx
  src/components/common/button/PurchaseReviewButton.jsx
  src/components/common/button/ReviewCompleteButton.jsx
  src/components/common/button/ReviewWriteButton.jsx
  src/components/common/button/SettingButton.jsx
  src/components/common/category/Category.jsx
  src/components/common/category/Category.style.js
  src/components/common/header/Header.style.js
  src/components/common/menu/menu.jsx
  src/components/common/topbar/Topbar.jsx
  src/components/common/topbar/Topbar.style.js
  src/components/logo/Logo.jsx
  src/components/modal/ModifyProfile.jsx
  src/components/mypage/LogoutStatus.style.js
  src/pages/Artist.jsx
  src/pages/ArtworkDetail.jsx
  src/pages/ArtworkUpload.jsx
  src/pages/ImageList.jsx
  src/pages/MyPage.jsx
  src/pages/Mypage.jsx
  src/pages/Review.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.style.js
  src/pages/artwork/artworkDetail/MyArtworkDetail.jsx
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
  src/pages/artwork/artworkUpload/ArtworkUpload.style.js
  src/pages/artworkDetail/ArtworkDetail.jsx
  src/pages/artworkDetail/MyArtworkDetail.jsx
  src/pages/artworkUpload/ArtworkUpload.jsx
  src/pages/auth/Auth.style.js
  src/pages/stack-grid.jsx
Labels: 기능, 공통, 완성

#102 Feature/#101
  src/Router.jsx
  src/assets/chatting/add.svg
  src/assets/chatting/send.svg
  src/assets/index.js
  src/components/chatting/ChattingInput.jsx
  src/components/chatting/ChattingInput.style.js
  src/components/common/bottomNav/BottomNav.jsx
  src/pages/chatting/Chatting.jsx
  src/pages/chatting/ChattingList.jsx
Labels: 페이지, 채팅, 완성

#109 feat: 내가 쓴 후기 컴포넌트 생성
  src/assets/index.js
  src/assets/myPage/more_vert.svg
  src/components/common/bar/PurchasedBar.jsx
  src/components/common/myPage/WrittenReview.jsx
  src/components/common/myPage/WrittenReview.style.js
  src/pages/ImageList.jsx
  src/pages/myPage/MyReview.jsx
  src/styles/color.js
Labels: 컴포넌트, 마이페이지

#110 feat: 마이페이지 생성
  src/assets/myPage/settings.svg
  src/components/common/button/MyArtWork.style.js
  src/components/common/button/SettingButton.jsx
  src/components/common/button/SettingButton.style.js
  src/components/common/menu/menu.jsx
  src/components/common/menu/menu.style.js
  src/components/common/myPage/MyArtWorkList.jsx
  src/components/common/myPage/PurchaseReviewList.jsx
  src/components/common/myPage/PurchaseReviewList.style.js
  src/components/modal/ModifyProfile.jsx
  src/components/modal/ModifyProfile.style.js
  src/components/mypage/LoginStatus.jsx
  src/components/mypage/LoginStatus.style.js
  src/constants/myReviewDummy.js
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyReview.jsx
Labels: 페이지, 마이페이지, 완성

#114 feat: 작품 등록 페이지 Topbar 추가
  src/components/common/topbar/Topbar.style.js
  src/pages/artwork/artworkUpload/ArtworkUpload.jsx
Labels: 페이지, 완성

#120 feat: 작품 상세 페이지 수정
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/artwork/artworkDetail/ArtworkDetail.style.js
  src/pages/artwork/artworkDetail/MyArtworkDetail.jsx
Labels: 페이지, 작품, 완성

#115 feat: 내가 쓴 후기 페이지 생성
  src/assets/index.js
  src/assets/myPage/trash.svg
  src/components/common/myPage/WrittenReview.jsx
  src/components/common/topbar/PurchasedTopbar.jsx
  src/components/common/topbar/Topbar.style.js
  src/components/modal/ModifyProfile.style.js
  src/components/modal/ReviewDelete.jsx
  src/components/modal/ReviewDetete.style.js
  src/constants/writtenReviewDummy.js
  src/pages/ImageList.jsx
  src/pages/myPage/MyReview.jsx
Labels: 페이지, 마이페이지, 완성

#116 feat: 후기 작성 페이지 생성
  src/assets/index.js
  src/components/common/artwork/ArtWorkInfo.jsx
  src/components/common/artwork/ArtWorkInfo.style.js
  src/components/common/button/ReviewButton.style.js
  src/components/common/button/WriteCompleteButton.jsx
  src/components/common/button/WriteCompleteButton.style.js
  src/components/common/myPage/ReviewDescription.jsx
  src/components/common/myPage/ReviewDescription.style.js
  src/pages/myPage/WriteReviewPage.jsx
Labels: 페이지, 마이페이지, 완성

#123 Feature/#92
  src/components/common/artwork/ArtWork.jsx
  src/components/common/header/Header.jsx
  src/components/common/topbar/SearchTopbar.jsx
  src/components/common/topbar/Topbar.style.js
  src/pages/artwork/artworkDetail/ArtworkDetail.jsx
  src/pages/main/Seach.jsx
  src/styles/font.js
Labels: 기능, 완성

#126 feat: columnArtworkList react-stack-grid 라이브러리 마이그레이션
  src/components/common/artworkList/ColumnArtworkList.jsx
Labels: 컴포넌트, 공통, 완성

#118 feat: api 세팅
  src/apis/api.js
  src/apis/user.js
  src/pages/auth/SignIn.jsx
Labels: 공통, 미완성
